# Generated by Django 5.2.7 on 2025-10-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vehicle_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dropoff_location',
            new_name='dropoff_address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_location',
            new_name='pickup_address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='weight',
            new_name='weight_kg',
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
