# Generated by Django 5.2.7 on 2025-10-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_dropoff_latitude_booking_dropoff_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_longitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='booking',
            name='goods_type',
            field=models.CharField(choices=[('small', 'Small Household Items'), ('large', 'Large Items / Furniture'), ('perishable', 'Perishable Goods')], default='small', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='weight',
            field=models.FloatField(default=0, help_text='Weight in kilograms'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackerping',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
        ),
        migrations.AlterField(
            model_name='trackerping',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('van', 'Van'), ('truck', 'Truck'), ('refrigerated', 'Refrigerated Truck')], max_length=20),
        ),
    ]
