# Generated by Django 5.2.7 on 2025-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_paid_at_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
