# Generated by Django 5.2.7 on 2025-10-19 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_amount_alter_payment_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 19, 21, 22, 5, 408426, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
