# Generated by Django 5.2.7 on 2025-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_booking_dropoff_lat_booking_dropoff_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='distance',
            field=models.FloatField(blank=True, help_text='Distance in kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='goods_type',
            field=models.CharField(choices=[('small', 'Small Household Items'), ('large', 'Large Items / Furniture'), ('perishable', 'Perishable Goods')], default='small', max_length=20),
        ),
    ]
