# Generated by Django 5.2.7 on 2025-11-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_booking_distance_alter_booking_goods_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='weight',
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='goods_type',
            field=models.CharField(choices=[('small', 'Small Household Items'), ('large', 'Large Items / Furniture'), ('perishable', 'Perishable Goods')], default='small', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
