# Generated by Django 5.2.7 on 2025-11-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_booking_weight_booking_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
