# Generated by Django 5.2.7 on 2025-11-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_booking_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_type', models.CharField(choices=[('van', 'Van Fleet'), ('truck', 'Truck Fleet'), ('refrigerated', 'Refrigerated Fleet')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('loader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number_plate', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('route_used', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='weight',
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expected_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fleet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='loader_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='route_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fleet'),
        ),
    ]
