# Generated by Django 5.2.7 on 2025-11-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fleet_remove_booking_weight_booking_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
