# Generated by Django 5.2.7 on 2025-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fleet_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='loader_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
