# Generated by Django 5.2.7 on 2025-11-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_booking_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_driver', to='core.driver'),
        ),
    ]
